[package]
name = "future-hs"
version = "0.1.0"
authors = ["ibaryshnikov"]
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies.tokio]
version = "1.37"
features = ["rt-multi-thread", "time"]
